create schema if not exists extension_store;
set schema 'extension_store';

-- create extensions table
create table extensions
(
    e_id                    integer generated by default as identity
        constraint "extensions_primary_key"
            primary key,
    e_package_id            text      not null,
    e_type                  integer   not null,
    e_name                  text      not null,
    e_category              text      not null,
    e_author                text      not null,
    e_description           text,
    e_github_repository     text      not null,
    e_discord_author_userid text,
    e_created_timestamp     timestamp not null,
    e_updated_timestamp     timestamp
);

alter table extensions
    owner to extensionstoremaster;

create index "extensions_e_category_index"
    on extensions (e_category);

create unique index "extensions_e_package_id_index"
    on extensions (e_package_id);

create index "extensions_e_type_index"
    on extensions (e_type);

-- create files table
create table files
(
    f_id                integer generated by default as identity
        constraint "files_primary_key"
            primary key,
    f_version           text      not null,
    f_min_api_version   integer   not null,
    f_pkg_filename      text      not null,
    f_icon_filename     text      not null,
    f_readme            text,
    f_file_hash         text      not null,
    f_license_name      text      not null,
    f_license_url       text      not null,
    e_ref               integer   not null
        constraint "files_extensions_e_ref_foreign_key"
            references extensions
            on delete cascade,
    f_created_timestamp timestamp not null
);

alter table files
    owner to extensionstoremaster;

create index "files_e_ref_index"
    on files (e_ref);

create index "files_f_version_index"
    on files (f_version);

-- create downloads table
create table downloads
(
    d_id                integer generated by default as identity
        constraint "downloads_primary_key"
            primary key,
    d_version           text      not null,
    e_ref               integer   not null
        constraint "downloads_extensions_e_ref_foreign_key"
            references extensions
            on delete cascade,
    d_created_timestamp timestamp not null
);

alter table downloads
    owner to extensionstoremaster;

create index "downloads_d_created_timestamp_index"
    on downloads (d_created_timestamp);

create index "downloads_d_version_index"
    on downloads (d_version);

create index "downloads_e_ref_index"
    on downloads (e_ref);

