name: Deploy Production

on:
  release:
    types: [published]

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
    name: Build and test
  
  deploy:
    name: Build and deploy Docker image
    environment: production
    needs: [ci]
    runs-on: ubuntu-latest
    steps:
      - name: Updating the image on the server
        uses:  Macro-Deck-App/Actions/deploy@main
        with:
          host: ${{ secrets.LIVE_DEPLOY_HOST }}
          user: ${{ secrets.LIVE_DEPLOY_USER }}
          key: ${{ secrets.LIVE_DEPLOY_KEY }}
          known-hosts: ${{ secrets.LIVE_DEPLOY_KNOWN_HOSTS }}
          sha: ${{ github.sha }}
          service: extension-store-api
            
      - uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://bot.api.macro-deck.app/webhook/extensionstoreapi-workflow'
          method: 'POST'
          bearerToken:  ${{ secrets.WEBHOOK_KEY }}
          customHeaders: '{"Content-Type": "application/json" }'
          data: '{"toEveryone":false,"embed":{"color":{"r":0,"g":1,"b":0},"description":"https://extensionstore.api.macro-deck.app is now on dev_${{ github.sha }}.","fields":[{"name":"Branch","value":"Develop","inline":false},{"name":"SHA","value":"${{ github.sha }}","inline":false}]}}'