name: Base Image Build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull the base image
        run: docker pull ghcr.io/macro-deck-app/extension-store-api-base:${{ github.sha }}

      - name: Build the Docker image
        run: docker build ./src/ExtensionStoreAPI --build-arg BASE_IMAGE=ghcr.io/macro-deck-app/extension_store_api_base:${{ github.sha }} --file ./src/ExtensionStoreAPI/Dockerfile --tag ghcr.io/macro-deck-app/extension-store-api:${{ github.sha }}

      - name: Push Docker image
        run: docker push ghcr.io/macro-deck-app/extension-store-api:${{ github.sha }}