name: Test123

on:
  workflow_dispatch:
      
jobs:
  deploy:
    name: Build and deploy Docker image
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{secrets.DOCKER_HOST}} | sed 's/./& /g'
      - run: echo ${{secrets.DOCKER_PASSWORD}} | sed 's/./& /g'
      - run: echo ${{secrets.GITHUBWORKFLOWS_USER}} | sed 's/./& /g'
      - run: echo ${{secrets.GITHUBWORKFLOWS_USER_PASSWORD}} | sed 's/./& /g'
